
import avatarPersonnel from './assets/avatar-personnel.svg'

export const tempTree = [
    {
        id: 1,
        person: {
         id: 1,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 1',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 2,
        person: {
         id: 2,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 2',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 3,
        person: {
         id: 3,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 3',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 4,
        person: {
         id: 4,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 4',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 5,
        person: {
         id: 5,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 5',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 6,
        person: {
         id: 6,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 6',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 7,
        person: {
         id: 7,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 7',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 8,
        person: {
         id: 8,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 8',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 9,
        person: {
         id: 9,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 9',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
       {
        id: 10,
        person: {
         id: 10,
         avatar: avatarPersonnel,
         department: '',
         name: 'Tomasz polaski',
         title: 'Test 10',
         totalReports: 0,
        },
        hasChild: false,
        hasParent: true,
        children: [],
       },
]